# 1. python image
FROM python:3.12-slim

# 2. Set environment variables to improve performance and prevent cache files
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# 3. Define working directory
WORKDIR /app

# 4. Install necessary system libraries (important for ChromaDB and SQLite)
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# 5. Copy requirements file first (to take advantage of cache when rebuilding)
COPY requirements.txt .

# 6. Install libraries (RAG_prouduction will be ignored thanks to .dockerignore file)
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# 7. Copy rest of project files (code, templates, database)
COPY . .
WORKDIR /app/src/rag_app
# 8. Expose port 80
EXPOSE 80

# 9. Run command
# We use host 0.0.0.0 so the external world can see the site
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
